'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Checkout

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txt_nrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nrp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_nrp_AutoCompleteExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nrp_AutoCompleteExtender As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txt_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nama As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_nohp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nohp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_keluarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_keluarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_keperluan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_keperluan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lokasi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_gedung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_gedung As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_kamar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_kamar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tujuan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tglcheckin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tglcheckin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_checkin_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_checkin_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txt_jamcheckin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_jamcheckin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_jamcheckin_MaskedEditExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_jamcheckin_MaskedEditExtender As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txt_tglcheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tglcheckout As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tglcheckout_CalendarExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tglcheckout_CalendarExtender As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txt_jamcheckout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_jamcheckout As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MaskedEditExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaskedEditExtender1 As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''btn_checkout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_checkout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ddl_carilokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_carilokasi As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_lokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_lokasi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txt_cari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cari As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gv_listpenghuni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_listpenghuni As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_listpenghuni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_listpenghuni As Global.System.Web.UI.WebControls.SqlDataSource
End Class
