'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Housekeeping

    '''<summary>
    '''ddl_lokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_lokasi As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_lokasi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_lokasi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddl_gedung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_gedung As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_gedung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_gedung As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_listkamar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_listkamar As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_listkamar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_listkamar As Global.System.Web.UI.WebControls.SqlDataSource
End Class
