'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_TicketEmergency

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''txt_kodebooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_kodebooking As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_servicefee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_servicefee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_maskapai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_maskapai As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_maskapai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_maskapai As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btn_one control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_one As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_pp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_pp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl_dari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dari As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tujuan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tanggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tanggal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_jam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_jam As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_jam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_jam As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_booking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_booking As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_booking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_booking As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ds_kelas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_kelas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_ketransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ketransit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_jamtransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_jamtransit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_jamtransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_jamtransit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_transit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_transit As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_bookingtransit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_bookingtransit As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''box_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents box_r2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_dari_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dari_r2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tujuan_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tujuan_r2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tanggal_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tanggal_r2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_jam_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_jam_r2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_jam_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_jam_r2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_booking_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_booking_r2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_booking_r2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_booking_r2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_ketransit_R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ketransit_R2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_jamtransit_R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_jamtransit_R2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_jamtransit_R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_jamtransit_R2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_transit_R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_transit_R2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_bookingtransit_R2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_bookingtransit_R2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddl_TA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_TA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_TA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txt_cari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cari As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gv_listTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_listTA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_listTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_listTA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btn_submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_submit As Global.System.Web.UI.WebControls.Button
End Class
