'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_ProsesRevisi_Ticket

    '''<summary>
    '''gv_listrevisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_listrevisi As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_revisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_revisi As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbl_noTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_noTA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_noST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_noST As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_nama control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_nama As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tanggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tanggal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_maskapai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_maskapai As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_dari control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dari As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tujuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tujuan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_kode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_kode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_revisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_revisi As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Tanggal_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Tanggal_Rev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_maskapai_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_maskapai_Rev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_dari_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dari_Rev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_tujuan_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tujuan_Rev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Ket_Rev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Ket_Rev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_agent As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_IdRev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_IdRev As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_submit As Global.System.Web.UI.WebControls.Button
End Class
