'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_AssignTA

    '''<summary>
    '''ddl_distrik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_distrik As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_distrik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_distrik As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddl_TA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_TA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_TA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_TA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddl_agent_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_agent_emergency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_Agent_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_Agent_emergency As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_emergency As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_emergency As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddl_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_agent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ds_Agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_Agent As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''gv_listTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_listTA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ds_listTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ds_listTA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btn_submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_submit As Global.System.Web.UI.WebControls.Button
End Class
