'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''row_gs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_gs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_kamarkosong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_kamarkosong As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_kamarkosong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_kamarkosong As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_kamarisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_kamarisi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_kamarterisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_kamarterisi As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_event control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_event As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_eventberlangsung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_eventberlangsung As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_ta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ta As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''row_pic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_pic As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_terlaksana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_terlaksana As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_eventterlaksana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_eventterlaksana As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_berlangsung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_berlangsung As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_eventberlangsung2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_eventberlangsung2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_kamar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_kamar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_kamarkosong2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_kamarkosong2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_konfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_konfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''row_agent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_agent As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_emergency As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_emergency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_emergency As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_booking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_booking As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_modif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_modif As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_revisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_revisi As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_revisi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_revisi As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_issued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_issued As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lk_issued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lk_issued As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
